### ISSUE TITLE
How to bind to simple date field?

### ISSUE THREAD

**Issue by AmirGilboa** [pokono/angular-dob#3]
I have users with a simple date filed: dateofbirth.
i need to bind the directive to that field.
i don't know why you decided to build this whole objects with separate fields for day, month, etc.
all i need is a simple way to bind to my date field.
(and i need it 2 way, so if i load a user with a dob, it needs to show in the control, like any other 2way binding control)
is there a way to do so?

thanks

**Comment by pokono** [comment]
As far as I understand you don't need this package. Have you solved the issue?
